/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FinancialTip = IDL.Record({ 'tip' : IDL.Text });
export const SideHustle = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timeCommitment' : IDL.Text,
  'category' : IDL.Text,
});
export const Profile = IDL.Record({
  'currentBalance' : IDL.Nat,
  'name' : IDL.Text,
  'monthlyGoal' : IDL.Nat,
});
export const SkillPath = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'potentialEarnings' : IDL.Nat,
});
export const EarningStrategy = IDL.Record({
  'title' : IDL.Text,
  'estimatedEarnings' : IDL.Nat,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const EarningsRecord = IDL.Record({
  'source' : IDL.Text,
  'date' : IDL.Int,
  'amount' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'askAIAdvice' : IDL.Func([IDL.Text], [IDL.Text], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllFinancialTips' : IDL.Func([], [IDL.Vec(FinancialTip)], ['query']),
  'getAllHustles' : IDL.Func([], [IDL.Vec(SideHustle)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getAllSkillPaths' : IDL.Func([], [IDL.Vec(SkillPath)], ['query']),
  'getAllStrategies' : IDL.Func([], [IDL.Vec(EarningStrategy)], ['query']),
  'getEarnings' : IDL.Func([], [IDL.Vec(EarningsRecord)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'isDataSeeded' : IDL.Func([], [IDL.Bool], ['query']),
  'logEarnings' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'seedData' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBalance' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FinancialTip = IDL.Record({ 'tip' : IDL.Text });
  const SideHustle = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timeCommitment' : IDL.Text,
    'category' : IDL.Text,
  });
  const Profile = IDL.Record({
    'currentBalance' : IDL.Nat,
    'name' : IDL.Text,
    'monthlyGoal' : IDL.Nat,
  });
  const SkillPath = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'potentialEarnings' : IDL.Nat,
  });
  const EarningStrategy = IDL.Record({
    'title' : IDL.Text,
    'estimatedEarnings' : IDL.Nat,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const EarningsRecord = IDL.Record({
    'source' : IDL.Text,
    'date' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'askAIAdvice' : IDL.Func([IDL.Text], [IDL.Text], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllFinancialTips' : IDL.Func([], [IDL.Vec(FinancialTip)], ['query']),
    'getAllHustles' : IDL.Func([], [IDL.Vec(SideHustle)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getAllSkillPaths' : IDL.Func([], [IDL.Vec(SkillPath)], ['query']),
    'getAllStrategies' : IDL.Func([], [IDL.Vec(EarningStrategy)], ['query']),
    'getEarnings' : IDL.Func([], [IDL.Vec(EarningsRecord)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'isDataSeeded' : IDL.Func([], [IDL.Bool], ['query']),
    'logEarnings' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'seedData' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBalance' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };