/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EarningStrategy {
  'title' : string,
  'estimatedEarnings' : bigint,
  'difficulty' : string,
  'description' : string,
  'category' : string,
}
export interface EarningsRecord {
  'source' : string,
  'date' : bigint,
  'amount' : bigint,
}
export interface FinancialTip { 'tip' : string }
export interface Profile {
  'currentBalance' : bigint,
  'name' : string,
  'monthlyGoal' : bigint,
}
export interface SideHustle {
  'title' : string,
  'description' : string,
  'timeCommitment' : string,
  'category' : string,
}
export interface SkillPath {
  'title' : string,
  'description' : string,
  'potentialEarnings' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'askAIAdvice' : ActorMethod<[string], string>,
  'createProfile' : ActorMethod<[string, bigint], undefined>,
  'getAllFinancialTips' : ActorMethod<[], Array<FinancialTip>>,
  'getAllHustles' : ActorMethod<[], Array<SideHustle>>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getAllSkillPaths' : ActorMethod<[], Array<SkillPath>>,
  'getAllStrategies' : ActorMethod<[], Array<EarningStrategy>>,
  'getEarnings' : ActorMethod<[], Array<EarningsRecord>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'isDataSeeded' : ActorMethod<[], boolean>,
  'logEarnings' : ActorMethod<[bigint, string], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBalance' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];